### ISSUE TITLE
[✨ Feature] 유저 매치 정보 조회

### ISSUE THREAD

**Issue by sjghub** [CA-DUO/FC-Online-Server#5]
**Is your feature request related to a problem? Please describe.**

## Description About Feature
유저 매치 정보 조회

## TODO
- [x] 유저 닉네임으로 고유 id 불러오기
- [x] 고유 id로 최근 매치 20개 불러오기
- [ ] 매치 상세 정보 불러오기
